#!/usr/bin/env sh

# [ -x "$(command -v foot)" ] && foot --server >/dev/null &
[ -x "$(command -v dunst)" ] && dunst >/dev/null &
[ -x "$(command -v kanshi)" ] && systemctl --user start kanshi >/dev/null &
[ -x "$(command -v notify-send)" ] && notify-send -t 1500 "Welcome back, sir!"
