#!/usr/bin/env sh

[ -x "$(command -v foot)" ] && foot --server >/dev/null &
[ -x "$(command -v dunst)" ] && dunst >/dev/null &
[ -x "$(command -v kanshi)" ] && kanshi >/dev/null &
[ -x "$(command -v notify-send)" ] && notify-send "Welcome back, sir!"
